apiVersion: v1
kind: Service
metadata:
  name: mosaic-site
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: mosaic-site-port
  type: LoadBalancer
  selector:
    app: mosaic-site
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosaic-site
spec:
  selector:
    matchLabels:
      app: mosaic-site
  template:
    metadata:
      labels:
        app: mosaic-site
    spec:
      containers:
        - name: mosaic-site
          image: mosaic-site
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 2
              memory: 1Gi
            limits:
              cpu: 2
              memory: 1Gi
