apiVersion: v1
kind: Service
metadata:
  name: mosaic-fs
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: mosaic-fs-port
  type: LoadBalancer
  selector:
    app: mosaic-fs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosaic-fs
spec:
  selector:
    matchLabels:
      app: mosaic-fs
  template:
    metadata:
      labels:
        app: mosaic-fs
    spec:
      volumes:
        - name: docs-volume
          emptyDir: {}
      containers:
        - name: mosaic-fs
          image: mosaic-fs
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: docs-volume
              mountPath: /app/docs
          resources:
            requests:
              cpu: 2
              memory: 1Gi
            limits:
              cpu: 2
              memory: 1Gi
